server:
  error:
    include-message: always
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://admin:123456789@localhost:27017/practicapragma
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

sonar:
  dynamicAnalysis: reuseReports
  host:
    url: http://localhost:9000
  jacoco:
    reportPath: build/test-reports/jacoco.exec
  java:
    coveragePlugin: jacoco
  junit:
    reportsPath: build/test-reports
  login: admin
  password: admin