server:
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/practicapragma
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxy-stream-allow-list:
      - 'localhost'

sonar:
  dynamicAnalysis: reuseReports
  host:
    url: http://localhost:9000
  jacoco:
    reportPath: build/test-reports/jacoco.exec
  java:
    coveragePlugin: jacoco
  junit:
    reportsPath: build/test-reports
  login: admin
  password: admin